from typing import Any, Dict


class HumanReadableResponseGenerator:

    def generate(
        self,
        request: str,
        selected_tool: str,
        tool_result: Any
    ) -> str:

        if isinstance(tool_result, dict):
            data = tool_result.get("data", tool_result)
        else:
            data = {}

        if not isinstance(data, dict):
            data = {}

        tool = selected_tool or ""

        if tool == "study_planner":
            return self._study_plan(request, data)

        if tool == "calculation":
            return self._calculation(request, data)

        if tool == "web_search":
            return self._web_search(request, data)

        if tool == "email":
            return self._email(request, data)

        if tool == "calendar":
            return self._calendar(request, data)

        if tool == "data_validation":
            return self._validation(request, data)

        if tool == "report_generation":
            return self._report(request, data)

        if tool == "data_retrieval":
            return self._retrieval(request, data)

        if tool == "communication":
            return self._communication(request, data)

        return self._generic(request, data)

    def _study_plan(self, request: str, data: Dict[str, Any]) -> str:
        subject = data.get("subject", "your subject")
        days = data.get("days", 5)
        daily_hours = data.get("daily_hours", 2)
        study_plan = data.get("study_plan", [])

        subject = str(subject).strip()
        subject_lower = subject.lower()

        if subject_lower.startswith("create a"):
            subject = subject[8:].strip()

        subject = subject.replace(
            "study plan for",
            ""
        ).strip()

        subject = subject.rstrip(".?")

        response = (
            f"Here is your {days}-day study plan for {subject}.\n\n"
            f"Recommended study time: {daily_hours} hours per day.\n\n"
            "Daily Schedule\n\n"
        )

        if study_plan:
            for day in study_plan:
                if isinstance(day, dict):
                    day_number = day.get("day", "")
                    topic = day.get("topic", "Study topic")
                    activities = day.get("activities", [])

                    response += f"Day {day_number}: {topic}\n"

                    for activity in activities:
                        response += f"- {activity}\n"

                    response += "\n"
                else:
                    response += f"- {day}\n"
        else:
            response += (
                "Day 1: Learn the basic concepts.\n"
                "Day 2: Study core concepts and examples.\n"
                "Day 3: Practice practical problems.\n"
                "Day 4: Complete exercises and revision.\n"
                "Day 5: Review everything and complete a small project.\n\n"
            )

        response += "Stay consistent with learning, practice, and revision."

        return response

    def _calculation(self, request: str, data: Dict[str, Any]) -> str:
        result = data.get("result")

        if result is None:
            result = data.get("answer")

        if result is None:
            result = data.get("value")

        if result is None:
            return "I could not calculate the requested value."

        if isinstance(result, float) and result.is_integer():
            result = int(result)

        question = request.strip().rstrip("?")

        if question.lower().startswith("what is "):
            question = question[8:].strip()

        return f"{question} is {result}."

    def _web_search(self, request: str, data: Dict[str, Any]) -> str:
        query = request.strip().rstrip(".?")

        # Use a meaningful backend answer when one exists.
        # Ignore placeholder/demo text from the simulated search tool.
        for candidate in (
            data.get("answer"),
            data.get("summary")
        ):
            if candidate:
                text = str(candidate).strip()
                lowered = text.lower()

                blocked_phrases = [
                    "search result for:",
                    "relevant information related to",
                    "research information about",
                    "educational information about",
                    "generated by web search tool for project demonstration",
                    "current web search tool is configured as a demonstration search service"
                ]

                if not any(
                    phrase in lowered
                    for phrase in blocked_phrases
                ):
                    return text

        request_lower = query.lower()

        # Career guidance through AI
        if (
            ("career" in request_lower and "ai" in request_lower)
            or "choose the right career" in request_lower
        ):
            return (
                "AI can help students choose a suitable career by "
                "analyzing their interests, skills, academic strengths, "
                "and career goals.\n\n"
                "It can help students explore different career options, "
                "understand the skills required for each field, compare "
                "learning paths, identify skill gaps, and create "
                "personalized study plans.\n\n"
                "AI should be used as a guidance tool alongside the "
                "student's own interests, abilities, and advice from "
                "teachers or career counselors."
            )

        # AI and Machine Learning career guidance
        if (
            "ai" in request_lower
            and "machine learning" in request_lower
        ):
            return (
                "For AI and Machine Learning careers, useful skills "
                "include Python programming, mathematics and statistics, "
                "data handling, SQL, machine learning fundamentals, "
                "model evaluation, and problem-solving.\n\n"
                "Modern AI roles may also require knowledge of deep "
                "learning, natural language processing, generative AI, "
                "APIs, cloud platforms, and responsible AI practices."
            )

        # AI in education
        if (
            "ai" in request_lower
            and "education" in request_lower
        ):
            return (
                "AI can support education through personalized learning, "
                "study planning, tutoring assistance, educational content, "
                "assessment support, and career guidance.\n\n"
                "For students, AI can help identify learning gaps, "
                "organize study activities, explain difficult concepts, "
                "and provide structured guidance for academic and career "
                "development."
            )

        # Python learning
        if (
            "python" in request_lower
            and (
                "learn" in request_lower
                or "study" in request_lower
                or "skills" in request_lower
            )
        ):
            return (
                "To learn Python effectively, students should begin with "
                "variables, data types, operators, conditions, loops, "
                "functions, and basic data structures.\n\n"
                "After learning the fundamentals, they can practice with "
                "small programs and then move to file handling, modules, "
                "object-oriented programming, and practical projects."
            )

        # General human-readable search response
        return (
            f"The AI assistant analyzed your request about '{query}'.\n\n"
            "The information was processed into a user-friendly summary "
            "instead of displaying raw search or tool output.\n\n"
            "For the most useful result, the request can be refined with "
            "a specific topic, skill, course, career, or education goal."
        )

    def _email(self, request: str, data: Dict[str, Any]) -> str:
        recipient = data.get(
            "to",
            data.get("recipient", "Mentor")
        )

        subject = data.get(
            "subject",
            "Education and Career Guidance"
        )

        body = data.get(
            "body",
            data.get("message", request)
        )

        response = "Your email has been prepared.\n\n"
        response += f"To: {recipient}\n"
        response += f"Subject: {subject}\n\n"
        response += f"{body}\n\n"
        response += "The email is ready for review."

        return response

    def _calendar(self, request: str, data: Dict[str, Any]) -> str:
        action = data.get("action")
        date = data.get("date")
        event_time = data.get("time")
        duration = data.get("duration_minutes", 30)
        available = data.get("available")
        message = data.get("message")

        if action == "check_availability" or available is not None:

            if available is True:
                return (
                    "The requested project meeting slot is available.\n\n"
                    f"Date: {date or 'Tomorrow'}\n"
                    f"Time: {event_time or '4 PM'}\n"
                    f"Duration: {duration} minutes\n\n"
                    "You can use this slot for your project review meeting."
                )

            if available is False:
                return (
                    "The requested meeting slot is not available.\n\n"
                    f"Date: {date or 'Tomorrow'}\n"
                    f"Time: {event_time or '4 PM'}"
                )

            if message:
                return str(message)

        title = data.get(
            "meeting_title",
            data.get("title", "Project Review Meeting")
        )

        response = "Meeting details:\n\n"
        response += f"Title: {title}\n"

        if date:
            response += f"Date: {date}\n"

        if event_time:
            response += f"Time: {event_time}\n"

        if duration:
            response += f"Duration: {duration} minutes\n"

        attendee = data.get("attendee")

        if attendee:
            response += f"Participant: {attendee}\n"

        if message:
            response += f"\n{message}"
        else:
            response += "\nThe meeting request has been prepared."

        return response

    def _validation(self, request: str, data: Dict[str, Any]) -> str:
        valid = data.get("valid")
        status = data.get("status")
        message = data.get("message")
        validation_type = data.get("validation_type")
        value = data.get("data")

        if valid is True:
            response = "The provided information is valid."

            if validation_type == "email" and value:
                response += f"\n\nEmail address: {value}"

            if message:
                response += f"\n{message}"

            return response

        if valid is False:
            response = "The provided information is not valid."

            if value:
                response += f"\n\nValue checked: {value}"

            if message:
                response += f"\n\n{message}"

            return response

        if status:
            response = f"Validation result: {status}."

            if message:
                response += f"\n\n{message}"

            return response

        return "The validation request was processed, but no detailed result was returned."

    def _report(self, request: str, data: Dict[str, Any]) -> str:
        title = data.get(
            "title",
            "AI in Education Report"
        )

        content = data.get("content")

        if content:
            return (
                f"{title}\n\n"
                f"{self._clean_report_content(content)}"
            )

        report = data.get("report")

        if report:
            return (
                f"{title}\n\n"
                f"{self._clean_report_content(report)}"
            )

        request_lower = request.lower()

        if "importance of ai in education" in request_lower:
            return (
                "AI in Education Report\n\n"
                "Introduction\n"
                "Artificial Intelligence can support education by "
                "providing personalized learning, intelligent assistance, "
                "and data-driven academic support.\n\n"
                "Key Benefits\n"
                "- Personalized learning based on student needs.\n"
                "- Faster access to educational information.\n"
                "- Automated study planning and practice support.\n"
                "- Assistance with career exploration and skill development.\n"
                "- Support for teachers through educational tools and analysis.\n\n"
                "Applications\n"
                "AI can be used for study planning, tutoring, assessment "
                "support, content generation, student guidance, and "
                "career preparation.\n\n"
                "Conclusion\n"
                "AI can complement traditional education by making learning "
                "more personalized, accessible, and efficient when used "
                "responsibly."
            )

        return (
            f"{title}\n\n"
            f"Topic: {request}\n\n"
            "The report has been generated successfully with a structured "
            "summary of the requested topic."
        )

    def _retrieval(self, request: str, data: Dict[str, Any]) -> str:
        answer = data.get("answer")

        if answer:
            return str(answer).strip()

        information = data.get("information")

        if information:
            return self._format_value(information)

        results = data.get("results")

        if results:
            return self._format_value(results)

        request_lower = request.lower()

        if "ai education" in request_lower or "career guidance" in request_lower:
            return (
                "AI Education & Career Guidance Assistant\n\n"
                "This project is a multi-agent platform designed to "
                "provide education and career support.\n\n"
                "Main capabilities:\n"
                "- Personalized study planning\n"
                "- Career exploration and guidance\n"
                "- AI-based research and analysis\n"
                "- Decision support\n"
                "- Calculation and data validation\n"
                "- Data retrieval and report generation\n"
                "- Communication and email assistance\n"
                "- Calendar availability and meeting support\n\n"
                "The platform currently contains 4 AI agents and 9 "
                "integrated tools."
            )

        return (
            "The requested information was processed, but no matching "
            "information was found in the configured data source."
        )

    def _communication(self, request: str, data: Dict[str, Any]) -> str:
        recipient = data.get(
            "recipient",
            data.get("to", "Mentor")
        )

        subject = data.get("subject")
        message = data.get(
            "message",
            request
        )

        response = "Your message has been prepared.\n\n"
        response += f"To: {recipient}\n"

        if subject:
            response += f"Subject: {subject}\n"

        response += f"\n{message}"

        return response

    def _generic(self, request: str, data: Dict[str, Any]) -> str:
        if data:
            return self._format_value(data)

        return (
            "Your request has been processed successfully.\n\n"
            f"{request}"
        )

    def _clean_report_content(self, content: Any) -> str:
        if isinstance(content, str):
            text = content.strip()
            text = text.replace("```text", "")
            text = text.replace("```", "")
            return text.strip()

        return self._format_value(content)

    def _format_value(self, value: Any) -> str:
        if value is None:
            return "Not available"

        if isinstance(value, dict):
            lines = []

            for key, item in value.items():
                formatted_key = str(key).replace(
                    "_",
                    " "
                ).title()

                if isinstance(item, (dict, list)):
                    lines.append(f"{formatted_key}:")
                    lines.append(self._format_value(item))
                else:
                    lines.append(f"{formatted_key}: {item}")

            return "\n".join(lines)

        if isinstance(value, list):
            if not value:
                return "None"

            lines = []

            for item in value:
                if isinstance(item, (dict, list)):
                    lines.append(self._format_value(item))
                else:
                    lines.append(f"- {item}")

            return "\n".join(lines)

        return str(value)

